- name: Configure db server
  hosts: db
  become: yes
  vars:
    login_host: 172.31.93.15
    mysql_root_password: "ExpenseApp@1"
  tasks:
  - name: Install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start service and enable service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install python mysql package
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11
# check password is already setup or not
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_info
  - name: print output
    ansible.builtin.debug:
      msg: "Output : {{ mysql_info }}"
  
  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
    when: mysql_info.failed is true
  